name: Python application

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run
        run: |
          curl -o data/workoutdata.csv ${{ secrets.EXERCISE_DATA }}
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv run python exercise.py
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
